/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-07-15 03:47:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Vistas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Clases.SociosDAO;
import Clases.Socios;
import java.util.List;

public final class modificar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Clases.SociosDAO");
    _jspx_imports_classes.add("Clases.Socios");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"h-100\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Modificar Socio</title>\r\n");
      out.write("<link rel = \"icon\" href=\"./img/logo.ico\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel = \"stylesheet\" href=\"./css/modificarEstilos.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"mb-3\">\r\n");
      out.write("\t<nav class=\"navbar\">\r\n");
      out.write("  \t<div class=\"container-fluid d-flex justify-content-center\">\r\n");
      out.write("\t    <a href=\"SociosController\"><img src=\"https://fontmeme.com/permalink/220713/67431d712ee8634df6ca3644989f5dcd.png\" alt=\"efecto-brillo\" border=\"0\"></a>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<h1 class=\"text-center\">Modificar Socio</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\" >\r\n");
      out.write("\t\t\t\t");

				String id=request.getParameter("id");
				int mid;
				mid=Integer.parseInt(id);				
				Socios resultado=null;
				SociosDAO  socio=new SociosDAO();
				resultado=socio.mostrarSocio(mid);				
				
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form name = \"actualizar\" class=\"p-5\" action=\"SociosController?accion=actualizar\" method=\"post\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"hidden\"  class=\"form-control\" id=\"id\" name=\"id\"  value=");
      out.print(resultado.getId_socio() );
      out.write(" >\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label for=\"nombre\" class=\"form-label\" >Nombre:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"nombre\" name=\"nombre\"  value=");
      out.print(resultado.getNombre() );
      out.write(" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label for=\"apellido\" class=\"form-label\" >Apellido:</label>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"apellido\" name=\"apellido\" value=");
      out.print(resultado.getApellido() );
      out.write(" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label for=\"dni\" class=\"form-label\" >DNI:</label>\r\n");
      out.write("\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"dni\" name=\"dni\" value=");
      out.print(resultado.getDni() );
      out.write(" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"mb-3\">\r\n");
      out.write("\t\t\t\t<label for=\"mail\" class=\"form-label\" >Mail:</label>\r\n");
      out.write("\t\t\t\t<input type=\"email\" class=\"form-control\" id=\"mail\" name=\"mail\" value=");
      out.print(resultado.getMail() );
      out.write(" required>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"form-check form-switch mt-3 d-flex\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<label for=\"estado\" class=\"form-check-label\" >Estado:</label>\r\n");
      out.write("\t\t\t\t\t<input class=\"form-check-input\" type=\"checkbox\" role=\"switch\" id=\"estado\" value=\"0\" name=\"estado\"  onclick=\"valor()\" ");
      out.print(resultado.getEstado() == 1?"checked":" " );
      out.write(">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<p class=\"mx-2 text-white\" id=\"ValorSegunCheck\"></p>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\tvar checkbox = document.getElementById(\"estado\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfunction checkboxValor(){\r\n");
      out.write("\t\t\t\t\t\tcheckbox.checked ? checkbox.value=\"1\":\"\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(document.getElementById(\"estado\").checked){\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"ValorSegunCheck\").innerHTML = 'Activo';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"ValorSegunCheck\").innerHTML = 'Inactivo';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tfunction valor(){\r\n");
      out.write("\t\t\t\t\t\tif(document.getElementById(\"estado\").checked){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"ValorSegunCheck\").innerHTML = 'Activo';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"ValorSegunCheck\").innerHTML = 'Inactivo';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-primary mt-2\" onclick=\"checkboxValor()\">Modificar</button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
