/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-07-15 19:10:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Vistas;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Clases.SociosDAO;
import Clases.Socios;
import java.util.List;

public final class socios_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Clases.SociosDAO");
    _jspx_imports_classes.add("Clases.Socios");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"h-100\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Socios del GYM</title>\r\n");
      out.write("<link rel = \"icon\" href=\"./img/logo.ico\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css\" integrity=\"sha512-10/jx2EXwxxWqCLX/hHth/vu2KY3jCF70dCQB8TSgNjbCVAC/8vai53GfMDrO2Emgwccf2pJqxct9ehpzG+MTw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel = \"stylesheet\" href=\"./css/sociosEstilos.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Titillium+Web&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"container-fluid\">\r\n");
      out.write("<header>\r\n");
      out.write("\t<nav class=\"navbar\">\r\n");
      out.write("\t  \t<div class=\"container-fluid d-flex justify-content-around\">\r\n");
      out.write("\t\t    <a class=\"navbar-brand d-flex align-items-center\" href=\"SociosController\">\r\n");
      out.write("\t\t      <img src=\"./img/logo.png\" alt=\"Logo\" width=\"100\" height=\"80\" class=\"d-inline-block\">\r\n");
      out.write("\t\t    </a>\r\n");
      out.write("\t\t    <a href=\"SociosController\"><img src=\"https://fontmeme.com/permalink/220713/67431d712ee8634df6ca3644989f5dcd.png\" alt=\"efecto-brillo\" border=\"0\"></a>\r\n");
      out.write("\t  \t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("</header>\r\n");
      out.write("<section class=\"main\">\r\n");
      out.write("<header>\r\n");
      out.write("\t<h2 class=\"text-center mb-5 mt-2\">Listado de Socios del GYM</h2>\r\n");
      out.write("\t<div class=\"container d-flex mt-2 mb-5\">\r\n");
      out.write("\t\t<div class=\"row d-flex justify-content-start\">\r\n");
      out.write("\t\t\t<form method=\"post\" class=\"row\" action=\"SociosController?accion\" method=\"post\">\r\n");
      out.write("\t\t\t\t<fieldset class=\"d-flex justify-content-start p-0\">\r\n");
      out.write("\t\t\t\t\t<label class=\"me-2 fs-3\" id=\"filtro\" for=\"filtroEstados\">Filtro:</label>\r\n");
      out.write("\t\t\t\t\t<select class=\"border-0 ms-2 p-2\" id=\"selectEstados\" name=\"filtroEstado\" id=\"filtroEstados\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" disabled selected>Estados</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"-1\">Todos</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">Activos</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"0\">Inactivos</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" name=\"submit\" id=\"enviarFiltroEstados\" class=\"ms-2 border-0\" value=\"Aplicar\">\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<section class=\"container-fluid h-100\">\r\n");
      out.write("\t<div  class=\"container h-100\" >\r\n");
      out.write("\t\t\t<div class=\"row h-100\" >\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-primary h-100\" >\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Nombre</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Apellido</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>DNI</th>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Fecha y Hora</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Estado</th>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\">Modificar</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th class=\"text-center\">Eliminar</th>\r\n");
      out.write("\t\t\t\t\t\t<tr>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t");

						
						List<Socios> resultado=null;
						SociosDAO socio=new SociosDAO();
						resultado=socio.listarSocios();
						
							
							for(int i=0;i<resultado.size();i++)
							{
								
								
								if(request.getParameter("filtroEstado") == null || Integer.parseInt(request.getParameter("filtroEstado")) == -1 || resultado.get(i).getEstado() == Integer.parseInt(request.getParameter("filtroEstado")))
								{
									String ruta="SociosController?accion=modificar&id="+resultado.get(i).getId_socio();	
									String rutaE="SociosController?accion=eliminar&id="+resultado.get(i).getId_socio();
							
					
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getId_socio());
      out.write("</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getNombre() );
      out.write("</td>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getApellido() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getDni());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getMail() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getFecha() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>");
      out.print(resultado.get(i).getEstadoNombre());
      out.write("</td>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\"><a href=");
      out.print(ruta);
      out.write("> <script src=\"https://cdn.lordicon.com/xdjxvujz.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<lord-icon\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    src=\"https://cdn.lordicon.com/sihdhmit.json\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    trigger=\"hover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    colors=\"primary:#121331\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    style=\"width:25px;height:25px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</lord-icon>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-center\"><a onclick=cambia_enlace() id=\"eliminar\" href=");
      out.print(rutaE);
      out.write("> <script src=\"https://cdn.lordicon.com/xdjxvujz.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<lord-icon\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    src=\"https://cdn.lordicon.com/dovoajyj.json\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    trigger=\"hover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    style=\"width:25px;height:25px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</lord-icon> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
 				
								}
						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction cambia_enlace(){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  var elemento = document.getElementById(\"eliminar\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  if(confirm('Desea continuar?')){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  elemento.href = \"SociosController\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("</section>\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"container mt-2 text-center\">\r\n");
      out.write("\t\t<a class=\"btn btn-primary col-4 m-4 border\" href=\"SociosController?accion=nuevo\">Agregar Socio</a>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</footer>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
